# Theme Settings
#
logo: /asset/something.png
feed: /atom.xml
google_analytics: UA-5000000-1
linkedin: http://linkedin/in/jasonamartin
twitter: http://twitter.com/jasonamartin
facebook:
instagram:
github: https://github.com/JasonAMartin/
pinterest:
